# Permalinks
permalink:           pretty

# Setup
title:               Tim Wilde
tagline:             'Developer'
description:         "I'm a full-stack, polyglot developer with a penchant for learning. I write code for all sorts of platforms including web, mobile, services, desktop, IoT, etc. This blog is about the things I learn along the way."
url:                 https://timwil.de
baseurl:             ''
paginate:            5

# Exclusions
exclude:            ['/breakanoid/CREDITS.md']

# About/contact
author:
  name:             Tim Wilde
  github:           timwilde
  url:              https://twitter.com/timwilde
  email:            blog@timwil.de
  gravatar:         https://www.gravatar.com/avatar/1c1ff25a3607719a16782ef5bc169422

service:
  disqus:           https://timwilde.disqus.com

# Custom vars
contact:
  twitter:          https://twitter.com/timwilde
  github:           https://github.com/timwilde

plugins:
 - jekyll-paginate
 - jekyll-gist
 - jekyll-sitemap
 - jekyll-avatar